apiVersion: canary.k8s.wantedly.com/v1beta1
kind: Canary
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: canary-sample
spec:
  targetDeploymentName: foo
  targetContainers: 
    - name: nginx
      image: nginx:latest
    - name: redis
      image: redis:5.0.5
